const selectInjectionActions = [
  { text: '甘精胰岛素(来得时)', value: 1 },
  { text: '甘精胰岛素(长秀霖)', value: 2 },
  { text: '地特胰岛素(诺和平)', value: 3 },
  { text: '中效胰岛素(诺和灵N)', value: 4 },
  { text: '中效胰岛素(优泌林N)', value: 5 },
  { text: '中效胰岛素(甘舒霖N)', value: 6 },
  { text: '中效胰岛素(优思灵N)', value: 7 },
  { text: '中效胰岛素(其他品牌)', value: 8 },
  { text: '短效胰岛素(诺和锐R)', value: 9 },
  { text: '短效胰岛素(优泌林R)', value: 10 },
  { text: '短效胰岛素(甘舒霖R)', value: 11 },
  { text: '短效胰岛素(优思灵R)', value: 12 },
  { text: '短效胰岛素(其他品牌)', value: 13 },
  { text: '门冬胰岛素(诺和锐)', value: 14 },
  { text: '门冬胰岛素(锐秀霖)', value: 15 },
  { text: '门冬胰岛素30(诺和锐30)', value: 16 },
  { text: '门冬胰岛素30(锐秀霖30)', value: 17 },
  { text: '门冬胰岛素50(诺和锐50)', value: 18 },
  { text: '赖脯胰岛素(优泌乐)', value: 19 },
  { text: '赖脯胰岛素(速秀霖)', value: 20 },
  { text: '谷赖胰岛素(艾倍得)', value: 21 },
  { text: '德谷胰岛素(诺和达)', value: 22 },
  { text: '德谷门冬双胰岛素(诺和佳)', value: 23 },
  { text: '预混人胰岛素(优泌林70/30)', value: 24 },
  { text: '预混人胰岛素(诺和灵30R)', value: 25 },
  { text: '预混人胰岛素(甘舒霖30R)', value: 26 },
  { text: '预混人胰岛素(优思灵30R)', value: 27 },
  { text: '预混人胰岛素(其他品牌30R)', value: 28 },
  { text: '预混人胰岛素(诺和灵50R)', value: 29 },
  { text: '预混人胰岛素(甘舒霖50R)', value: 30 },
  { text: '预混人胰岛素(优思灵50R)', value: 31 },
  { text: '预混人胰岛素(其他品牌50R)', value: 32 },
  { text: '预混赖脯胰岛素25(优泌乐25)', value: 33 },
  { text: '预混赖脯胰岛素25(速秀霖25)', value: 34 },
  { text: '预混赖脯胰岛素50(优泌乐50)', value: 35 },
  { text: '甘精胰岛素(优乐灵)', value: 36 },
  { text: '其他(可自己输入)', value: 37 }
]

export default selectInjectionActions
